# Generated by Django 2.0.7 on 2018-09-29 18:21

import datetime
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180930_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Last_Update',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 18, 21, 28, 27934, tzinfo=datetime.timezone.utc)),
        ),
    ]
