# Generated by Django 4.2 on 2025-07-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_securitysettings_enable_ttl_modification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(max_length=64, unique=True, verbose_name='Device Fingerprint ID')),
                ('User_Agent', models.TextField(verbose_name='User Agent String')),
                ('Screen_Resolution', models.CharField(blank=True, max_length=20, null=True, verbose_name='Screen Resolution')),
                ('Browser_Language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Browser Language')),
                ('Timezone_Offset', models.IntegerField(blank=True, null=True, verbose_name='Timezone Offset')),
                ('Platform', models.CharField(blank=True, max_length=50, null=True, verbose_name='Platform/OS')),
                ('Default_TTL_Pattern', models.IntegerField(blank=True, null=True, verbose_name='Consistent TTL Value')),
                ('Connection_Behavior', models.JSONField(default=dict, verbose_name='Connection Patterns')),
                ('First_Seen', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('Last_Seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('Device_Status', models.CharField(choices=[('active', 'Active'), ('suspicious', 'Suspicious'), ('blocked', 'Blocked'), ('whitelist', 'Whitelisted')], default='active', max_length=20)),
                ('Known_MACs', models.JSONField(default=list, verbose_name='Associated MAC Addresses')),
                ('Current_MAC', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current MAC Address')),
                ('MAC_Randomization_Detected', models.BooleanField(default=False, verbose_name='Uses MAC Randomization')),
                ('Total_TTL_Violations', models.IntegerField(default=0, verbose_name='Total TTL Violations')),
                ('Total_Connection_Violations', models.IntegerField(default=0, verbose_name='Connection Limit Violations')),
                ('Last_Violation_Date', models.DateTimeField(blank=True, null=True, verbose_name='Last Violation')),
                ('Device_Name_Hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Name Hint')),
                ('Admin_Notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'ordering': ['-Last_Seen'],
            },
        ),
    ]
