# Generated by Django 4.2 on 2025-07-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_unauthenticatedclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.ledger',),
        ),
    ]
