# Generated by Django 5.1.5 on 2025-07-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_salesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version_Number', models.CharField(max_length=20, verbose_name='Version Number')),
                ('Update_Title', models.CharField(max_length=255, verbose_name='Update Title')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Release_Date', models.DateTimeField(verbose_name='Release Date')),
                ('Download_URL', models.URLField(default='https://github.com/regolet/pisowifi', max_length=500, verbose_name='Download URL')),
                ('File_Size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('Status', models.CharField(choices=[('checking', 'Checking for Updates'), ('available', 'Update Available'), ('downloading', 'Downloading Update'), ('ready', 'Ready to Install'), ('installing', 'Installing Update'), ('completed', 'Update Completed'), ('failed', 'Update Failed'), ('rollback', 'Rolling Back')], default='checking', max_length=20, verbose_name='Status')),
                ('Progress', models.IntegerField(default=0, verbose_name='Progress (%)')),
                ('Downloaded_Bytes', models.BigIntegerField(default=0, verbose_name='Downloaded Bytes')),
                ('Started_At', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('Completed_At', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('Error_Message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('Backup_Path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Backup Path')),
                ('Is_Auto_Update', models.BooleanField(default=False, verbose_name='Auto Update')),
                ('Force_Update', models.BooleanField(default=False, verbose_name='Force Update')),
                ('Created_At', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('Updated_At', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'System Update',
                'verbose_name_plural': 'System Updates',
                'ordering': ['-Created_At'],
            },
        ),
        migrations.CreateModel(
            name='UpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GitHub_Repository', models.CharField(default='regolet/pisowifi', max_length=255, verbose_name='GitHub Repository')),
                ('Check_Interval_Hours', models.IntegerField(default=24, verbose_name='Check Interval (hours)')),
                ('Auto_Download', models.BooleanField(default=False, verbose_name='Auto Download Updates')),
                ('Auto_Install', models.BooleanField(default=False, verbose_name='Auto Install Updates')),
                ('Backup_Before_Update', models.BooleanField(default=True, verbose_name='Backup Before Update')),
                ('Max_Backup_Count', models.IntegerField(default=3, verbose_name='Maximum Backup Count')),
                ('Last_Check', models.DateTimeField(blank=True, null=True, verbose_name='Last Check')),
                ('Current_Version', models.CharField(default='1.0.0', max_length=20, verbose_name='Current Version')),
                ('Update_Channel', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('dev', 'Development')], default='stable', max_length=20, verbose_name='Update Channel')),
            ],
            options={
                'verbose_name': 'Update Settings',
                'verbose_name_plural': 'Update Settings',
            },
        ),
        migrations.AlterField(
            model_name='adaptiveqosrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blockeddevices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coinqueue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coinslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='connectiontracker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicebehaviorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='network',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='networkintelligence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trafficmonitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ttlfirewallrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
