# Generated by Django 5.1.5 on 2025-07-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_systemupdate_updatesettings_alter_adaptiveqosrule_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdate',
            name='Installation_Log',
            field=models.TextField(blank=True, null=True, verbose_name='Installation Log'),
        ),
    ]
