# Generated by Django 5.1.5 on 2025-07-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_systemupdate_installation_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemupdate',
            name='Installation_Log',
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Backup_Name', models.CharField(max_length=255, verbose_name='Backup Name')),
                ('Backup_Type', models.CharField(choices=[('manual', 'Manual Backup'), ('auto_update', 'Auto Update Backup'), ('scheduled', 'Scheduled Backup')], default='manual', max_length=20, verbose_name='Backup Type')),
                ('Status', models.CharField(choices=[('creating', 'Creating Backup'), ('completed', 'Completed'), ('failed', 'Failed'), ('restoring', 'Restoring'), ('restored', 'Restored')], default='creating', max_length=20, verbose_name='Status')),
                ('Backup_Path', models.CharField(max_length=500, verbose_name='Backup Path')),
                ('Backup_Size', models.BigIntegerField(default=0, verbose_name='Backup Size (bytes)')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('Created_At', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('Created_By', models.CharField(default='System', max_length=100, verbose_name='Created By')),
                ('Restored_At', models.DateTimeField(blank=True, null=True, verbose_name='Restored At')),
                ('Restored_By', models.CharField(blank=True, max_length=100, null=True, verbose_name='Restored By')),
                ('Error_Message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('Has_Database', models.BooleanField(default=True, verbose_name='Includes Database')),
                ('Has_Code', models.BooleanField(default=True, verbose_name='Includes Code')),
                ('Has_Static', models.BooleanField(default=True, verbose_name='Includes Static Files')),
                ('Has_Media', models.BooleanField(default=False, verbose_name='Includes Media Files')),
                ('Related_Update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.systemupdate', verbose_name='Related Update')),
            ],
            options={
                'verbose_name': 'System Backup',
                'verbose_name_plural': 'System Backups',
                'ordering': ['-Created_At'],
            },
        ),
    ]
