# Generated by Django 5.1.5 on 2025-07-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_remove_systemupdate_installation_log_systembackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdate',
            name='Installation_Log',
            field=models.TextField(blank=True, null=True, verbose_name='Installation Log'),
        ),
    ]
