# Generated by Django 5.1.5 on 2025-07-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_systemupdate_installation_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemBackup',
        ),
    ]
