# Generated by Django 5.1.5 on 2025-07-30 14:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_delete_systembackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='Validity_Days',
            field=models.IntegerField(default=0, help_text='Number of days the purchased time is valid. 0 = no expiration', verbose_name='Validity Period (Days)'),
        ),
        migrations.AddField(
            model_name='rates',
            name='Validity_Hours',
            field=models.IntegerField(default=0, help_text='Additional hours for validity period. Combined with days above.', verbose_name='Validity Period (Hours)'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='Voucher_code',
            field=models.CharField(blank=True, default=app.models.Vouchers.generate_code, max_length=20, unique=True),
        ),
    ]
