# Generated by Django 5.1.5 on 2025-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_rates_validity_days_rates_validity_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Validity_Expires_On',
            field=models.DateTimeField(blank=True, help_text='When purchased time expires and can no longer be used', null=True, verbose_name='Validity Expiration'),
        ),
    ]
