# Generated by Django 5.1.5 on 2025-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_clients_validity_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='Validity_Days',
            field=models.IntegerField(default=0, help_text='Number of days the voucher time is valid once redeemed. 0 = no expiration', verbose_name='Validity Period (Days)'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='Validity_Hours',
            field=models.IntegerField(default=0, help_text='Additional hours for validity period. Combined with days above.', verbose_name='Validity Period (Hours)'),
        ),
    ]
