# Generated by Django 5.1.5 on 2025-07-30 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_vouchers_validity_days_vouchers_validity_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Default_Block_Duration',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Default duration for blocking devices. Format: HH:MM:SS (e.g., 24:00:00 for 24 hours)', verbose_name='Default Block Duration'),
        ),
    ]
