# Generated by Django 5.1.5 on 2025-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_settings_default_block_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeddevices',
            name='Is_Permanent',
            field=models.BooleanField(default=False, help_text='If enabled, device will remain blocked indefinitely', verbose_name='Permanent Block'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Enable_Permanent_Block',
            field=models.BooleanField(default=False, help_text='Allow devices to be blocked permanently (no auto-unblock)', verbose_name='Enable Permanent Block Option'),
        ),
    ]
