# Generated by Django 5.1.5 on 2025-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_update_current_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auto_Backup_Enabled', models.BooleanField(default=True, verbose_name='Enable Auto Backup')),
                ('Auto_Backup_Interval_Hours', models.IntegerField(default=24, verbose_name='Auto Backup Interval (hours)')),
                ('Max_Backup_Count', models.IntegerField(default=10, verbose_name='Maximum Backup Count')),
                ('Backup_Location', models.CharField(default='backups/database/', max_length=500, verbose_name='Backup Directory')),
                ('Include_Client_Data', models.BooleanField(default=True, verbose_name='Include Client Data in Auto Backup')),
                ('Include_System_Settings', models.BooleanField(default=True, verbose_name='Include System Settings in Auto Backup')),
                ('Include_Logs', models.BooleanField(default=False, verbose_name='Include Logs in Auto Backup')),
                ('Compress_Backups', models.BooleanField(default=True, verbose_name='Compress Backup Files')),
                ('Retention_Days', models.IntegerField(default=30, verbose_name='Backup Retention (days)')),
                ('Email_Notifications', models.BooleanField(default=False, verbose_name='Email Backup Notifications')),
                ('Email_Recipients', models.TextField(blank=True, help_text='Email addresses separated by commas', verbose_name='Email Recipients')),
                ('Last_Auto_Backup', models.DateTimeField(blank=True, null=True, verbose_name='Last Auto Backup')),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=255, verbose_name='Backup Name')),
                ('backup_type', models.CharField(choices=[('full', 'Full Database'), ('clients', 'Clients Data Only'), ('settings', 'System Settings Only'), ('custom', 'Custom Selection')], default='full', max_length=20, verbose_name='Backup Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='File Path')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('compressed', models.BooleanField(default=False, verbose_name='Compressed')),
                ('tables_included', models.TextField(blank=True, verbose_name='Tables Included')),
                ('records_count', models.IntegerField(default=0, verbose_name='Total Records')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Progress %')),
                ('current_operation', models.CharField(blank=True, max_length=255, verbose_name='Current Operation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Created By')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='updatesettings',
            name='Current_Version',
            field=models.CharField(default='2.0.1', max_length=20, verbose_name='Current Version'),
        ),
    ]
