# Generated by Django 5.1.5 on 2025-07-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_add_database_backup_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLANSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_mode', models.CharField(choices=[('usb_to_lan', 'USB to LAN Mode'), ('vlan', 'VLAN Mode')], default='usb_to_lan', max_length=20, verbose_name='Network Mode')),
                ('vlan_id', models.IntegerField(default=22, help_text='VLAN ID for VLAN mode (1-4094)', verbose_name='VLAN ID')),
                ('eth_interface', models.CharField(default='eth0', max_length=20, verbose_name='Ethernet Interface')),
                ('usb_interface', models.CharField(default='wlan0', max_length=20, verbose_name='USB WiFi Interface')),
                ('auto_restart_on_change', models.BooleanField(default=True, verbose_name='Auto Restart on Network Mode Change')),
                ('current_status', models.CharField(default='USB to LAN Mode Active', max_length=50, verbose_name='Current Status')),
                ('last_mode_change', models.DateTimeField(blank=True, null=True, verbose_name='Last Mode Change')),
            ],
            options={
                'verbose_name': 'VLAN Settings',
                'verbose_name_plural': 'VLAN Settings',
            },
        ),
    ]
