# Generated by Django 5.1.5 on 2025-07-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_vlansettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroTierMonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('network_online', models.BooleanField(default=False)),
                ('zerotier_version', models.CharField(blank=True, max_length=50)),
                ('node_id', models.CharField(blank=True, max_length=10)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.FloatField(blank=True, null=True)),
                ('connected_clients', models.IntegerField(default=0)),
                ('total_bandwidth_up', models.BigIntegerField(default=0)),
                ('total_bandwidth_down', models.BigIntegerField(default=0)),
                ('active_vouchers', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coin_queue_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ZeroTier Monitoring Data',
                'verbose_name_plural': 'ZeroTier Monitoring Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ZeroTierSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(blank=True, help_text='API token from ZeroTier Central (my.zerotier.com)', max_length=64, verbose_name='ZeroTier API Token')),
                ('central_url', models.URLField(default='https://my.zerotier.com', verbose_name='ZeroTier Central URL')),
                ('network_id', models.CharField(blank=True, help_text='ZeroTier network ID to join (16 characters)', max_length=16, verbose_name='Network ID')),
                ('network_name', models.CharField(blank=True, help_text='Descriptive name for this network', max_length=100, verbose_name='Network Name')),
                ('device_name', models.CharField(default='PisoWiFi-System', help_text='Name for this PisoWiFi system in ZeroTier network', max_length=100, verbose_name='Device Name')),
                ('device_description', models.TextField(blank=True, help_text='Description of this PisoWiFi installation', verbose_name='Device Description')),
                ('enable_monitoring', models.BooleanField(default=False, help_text='Allow remote monitoring of this system via ZeroTier', verbose_name='Enable Remote Monitoring')),
                ('auto_authorize', models.BooleanField(default=True, help_text='Automatically authorize this device when joining network', verbose_name='Auto-Authorize Device')),
                ('monitoring_interval', models.IntegerField(default=300, help_text='How often to update monitoring data (default: 5 minutes)', verbose_name='Monitoring Interval (seconds)')),
                ('connection_status', models.CharField(default='Disconnected', max_length=20, verbose_name='Connection Status')),
                ('zerotier_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ZeroTier IP Address')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('last_monitoring_update', models.DateTimeField(blank=True, null=True, verbose_name='Last Monitoring Update')),
            ],
            options={
                'verbose_name': 'ZeroTier Remote Monitoring',
                'verbose_name_plural': 'ZeroTier Remote Monitoring',
            },
        ),
    ]
