# Generated by Django 5.1.5 on 2025-07-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_zerotiermonitoringdata_zerotiersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerotiermonitoringdata',
            name='node_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zerotiermonitoringdata',
            name='zerotier_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
