# Generated by Django 5.1.5 on 2025-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_alter_zerotiermonitoringdata_node_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='Client_Download_Rate',
            field=models.IntegerField(blank=True, help_text='Default download bandwidth limit for each client in Kbps. No value = unlimited bandwidth', null=True, verbose_name='Download Bandwidth per Client'),
        ),
        migrations.AddField(
            model_name='network',
            name='Client_Upload_Rate',
            field=models.IntegerField(blank=True, help_text='Default upload bandwidth limit for each client in Kbps. No value = unlimited bandwidth', null=True, verbose_name='Upload Bandwidth per Client'),
        ),
        migrations.AlterField(
            model_name='zerotiersettings',
            name='api_token',
            field=models.CharField(blank=True, help_text='API token from ZeroTier Central (my.zerotier.com) - Optional: only needed for advanced management features', max_length=64, verbose_name='ZeroTier API Token'),
        ),
        migrations.AlterField(
            model_name='zerotiersettings',
            name='network_id',
            field=models.CharField(blank=True, help_text='ZeroTier network ID to join (16 characters) - Required for basic connectivity', max_length=16, verbose_name='Network ID'),
        ),
    ]
