# Generated by Django 5.1.5 on 2025-07-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0129_add_client_bandwidth_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='Client_Download_Rate',
            field=models.IntegerField(blank=True, default=5000, help_text='Default download bandwidth limit for each client in Kbps. Default: 5 Mbps (5000 Kbps)', null=True, verbose_name='Download Bandwidth per Client'),
        ),
        migrations.AlterField(
            model_name='network',
            name='Client_Upload_Rate',
            field=models.IntegerField(blank=True, default=5000, help_text='Default upload bandwidth limit for each client in Kbps. Default: 5 Mbps (5000 Kbps)', null=True, verbose_name='Upload Bandwidth per Client'),
        ),
        migrations.AlterField(
            model_name='network',
            name='Download_Rate',
            field=models.IntegerField(blank=True, default=100000, help_text='Specify global internet download bandwidth in Kbps. Default: 100 Mbps (100000 Kbps)', null=True, verbose_name='Download Bandwidth'),
        ),
        migrations.AlterField(
            model_name='network',
            name='Upload_Rate',
            field=models.IntegerField(blank=True, default=100000, help_text='Specify global internet upload bandwidth in Kbps. Default: 100 Mbps (100000 Kbps)', null=True, verbose_name='Upload Bandwidth'),
        ),
    ]
