# Generated by Django 5.1.5 on 2025-07-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0130_set_default_bandwidth_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='WAN_IP',
            field=models.GenericIPAddressField(blank=True, help_text='Automatically detected external/public IP address', null=True, verbose_name='WAN IP Address'),
        ),
        migrations.AddField(
            model_name='network',
            name='WAN_Last_Updated',
            field=models.DateTimeField(blank=True, help_text='When the WAN IP was last detected', null=True, verbose_name='WAN IP Last Updated'),
        ),
    ]
