# Generated by Django 5.1.5 on 2025-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_add_wan_ip_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortPrioritization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('traffic_type', models.CharField(choices=[('browsing', 'Web Browsing'), ('gaming', 'Gaming'), ('streaming', 'Video Streaming'), ('voip', 'Voice/Video Calls'), ('downloading', 'File Downloads'), ('p2p', 'P2P/Torrenting'), ('social', 'Social Media'), ('email', 'Email'), ('custom', 'Custom Application')], max_length=20, verbose_name='Traffic Type')),
                ('priority_level', models.CharField(choices=[('critical', 'Critical (1)'), ('high', 'High (2)'), ('normal', 'Normal (3)'), ('low', 'Low (4)')], default='normal', max_length=10, verbose_name='Priority Level')),
                ('ports', models.CharField(help_text='Comma-separated ports/ranges (e.g., 80,443,8000-9000)', max_length=500, verbose_name='Ports')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('both', 'Both')], default='both', max_length=10, verbose_name='Protocol')),
                ('guaranteed_bandwidth_up', models.IntegerField(blank=True, help_text='Minimum guaranteed upload bandwidth', null=True, verbose_name='Guaranteed Upload (Kbps)')),
                ('guaranteed_bandwidth_down', models.IntegerField(blank=True, help_text='Minimum guaranteed download bandwidth', null=True, verbose_name='Guaranteed Download (Kbps)')),
                ('max_bandwidth_up', models.IntegerField(blank=True, help_text='Maximum upload bandwidth limit', null=True, verbose_name='Max Upload (Kbps)')),
                ('max_bandwidth_down', models.IntegerField(blank=True, help_text='Maximum download bandwidth limit', null=True, verbose_name='Max Download (Kbps)')),
                ('dscp_marking', models.IntegerField(blank=True, help_text='DSCP value for packet marking (0-63)', null=True, verbose_name='DSCP Marking')),
                ('burst_allowance', models.IntegerField(default=10, help_text='Percentage above guaranteed bandwidth allowed in bursts', verbose_name='Burst Allowance (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('apply_to_all_clients', models.BooleanField(default=True, help_text='Apply this rule to all clients by default', verbose_name='Apply to All Clients')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Port Prioritization Rule',
                'verbose_name_plural': 'Port Prioritization Rules',
                'ordering': ['priority_level', 'rule_name'],
            },
        ),
        migrations.AlterField(
            model_name='network',
            name='WAN_IP',
            field=models.GenericIPAddressField(blank=True, help_text='IP address assigned by router to this system (e.g., 192.168.1.x)', null=True, verbose_name='WAN IP Address'),
        ),
    ]
