# Generated by Django 5.1.5 on 2025-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_portprioritization_alter_network_wan_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Banner Name')),
                ('banner_type', models.CharField(choices=[('carousel', 'Carousel Banner'), ('header', 'Header Banner'), ('footer', 'Footer Banner'), ('popup', 'Popup Banner')], default='carousel', max_length=20, verbose_name='Banner Type')),
                ('image', models.ImageField(upload_to='portal/banners/', verbose_name='Banner Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt Text')),
                ('link_url', models.URLField(blank=True, help_text='URL to redirect when banner is clicked', verbose_name='Link URL')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Open in New Tab')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('max_width', models.IntegerField(default=1200, verbose_name='Max Width (px)')),
                ('max_height', models.IntegerField(default=400, verbose_name='Max Height (px)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Banner',
                'verbose_name_plural': 'Portal Banners',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_title', models.CharField(default='PISOWifi Portal', max_length=100, verbose_name='Portal Title')),
                ('portal_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Portal Subtitle')),
                ('hotspot_name', models.CharField(max_length=255, verbose_name='Hotspot Name')),
                ('hotspot_address', models.CharField(blank=True, max_length=255, verbose_name='Hotspot Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portal/logos/', verbose_name='Portal Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='portal/favicons/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex color code (e.g., #007bff)', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code (e.g., #6c757d)', max_length=7, verbose_name='Secondary Color')),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color code (e.g., #ffffff)', max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(default='#212529', help_text='Hex color code (e.g., #212529)', max_length=7, verbose_name='Text Color')),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect after successful connection', verbose_name='Redirect URL')),
                ('show_timer', models.BooleanField(default=True, help_text='Display remaining time countdown', verbose_name='Show Timer')),
                ('show_data_usage', models.BooleanField(default=True, help_text='Display data usage information', verbose_name='Show Data Usage')),
                ('auto_refresh_interval', models.IntegerField(default=30, help_text='Page auto-refresh interval in seconds', verbose_name='Auto Refresh Interval (seconds)')),
                ('enable_vouchers', models.BooleanField(default=True, verbose_name='Enable Vouchers')),
                ('enable_pause_resume', models.BooleanField(default=True, verbose_name='Enable Pause/Resume')),
                ('enable_social_login', models.BooleanField(default=False, verbose_name='Enable Social Login')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Maintenance Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Settings',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
        migrations.CreateModel(
            name='PortalAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Audio Name')),
                ('audio_type', models.CharField(choices=[('background', 'Background Music'), ('coin_insert', 'Coin Insert Sound'), ('coin_accepted', 'Coin Accepted Sound'), ('connection_success', 'Connection Success Sound'), ('connection_failed', 'Connection Failed Sound'), ('time_warning', 'Time Warning Sound'), ('disconnection', 'Disconnection Sound')], max_length=20, verbose_name='Audio Type')),
                ('audio_file', models.FileField(help_text='Supported formats: MP3, WAV, OGG', upload_to='portal/audio/', verbose_name='Audio File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('volume', models.IntegerField(default=50, help_text='Volume level (0-100)', verbose_name='Volume (%)')),
                ('loop', models.BooleanField(default=False, help_text='Loop audio continuously (for background music)', verbose_name='Loop Audio')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Audio',
                'verbose_name_plural': 'Portal Audio Files',
                'unique_together': {('audio_type', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='PortalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Text Name')),
                ('text_type', models.CharField(choices=[('welcome_message', 'Welcome Message'), ('instructions', 'Connection Instructions'), ('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('help_text', 'Help Text'), ('contact_info', 'Contact Information'), ('footer_text', 'Footer Text'), ('error_messages', 'Error Messages'), ('success_messages', 'Success Messages')], max_length=20, verbose_name='Text Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('allow_html', models.BooleanField(default=False, help_text='Allow HTML tags in content', verbose_name='Allow HTML')),
                ('font_size', models.CharField(blank=True, help_text='CSS font size (e.g., 16px, 1.2em)', max_length=10, verbose_name='Font Size')),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('lighter', 'Lighter')], default='normal', max_length=10, verbose_name='Font Weight')),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', max_length=10, verbose_name='Text Alignment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, es, fr)', max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Text',
                'verbose_name_plural': 'Portal Texts',
                'ordering': ['text_type', 'display_order'],
                'unique_together': {('text_type', 'language', 'is_active')},
            },
        ),
    ]
