# Generated by Django 5.1.5 on 2025-07-31 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_portalbanner_portalsettings_portalaudio_portaltext'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portalaudio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='pause_resume_min_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Minimum remaining time required to enable pause button (HH:MM:SS format)', null=True, verbose_name='Minimum Time for Pause'),
        ),
    ]
