# Generated by Django 5.1.5 on 2025-07-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0134_alter_portalaudio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'WIFI Settings', 'verbose_name_plural': 'WIFI Settings'},
        ),
        migrations.AddField(
            model_name='portalbanner',
            name='portal_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='app.portalsettings', verbose_name='Portal Settings'),
        ),
    ]
