# Generated by Django 5.1.5 on 2025-07-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_alter_settings_options_portalbanner_portal_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalaudio',
            name='portal_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='app.portalsettings', verbose_name='Portal Settings'),
        ),
    ]
