# Generated by Django 5.1.5 on 2025-07-31 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_portalaudio_portal_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerotiermonitoringdata',
            name='zerotier_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_data', to='app.zerotiersettings', verbose_name='ZeroTier Settings'),
        ),
    ]
