# Generated by Django 5.1.5 on 2025-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_zerotiermonitoringdata_zerotier_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Coin Rate', 'verbose_name_plural': 'Coin Rates'},
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='slot_timeout',
            field=models.IntegerField(default=300, help_text='Slot timeout in seconds. Time limit for coin insertion and login process.', verbose_name='Slot Timeout'),
        ),
    ]
