# Generated by Django 5.1.5 on 2025-07-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_move_slot_timeout_to_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlansettings',
            name='vlan_id',
            field=models.IntegerField(blank=True, default=22, help_text='VLAN ID for VLAN mode (1-4094). Leave blank for USB to LAN mode.', null=True, verbose_name='VLAN ID'),
        ),
    ]
