# Generated by Django 4.2.23 on 2025-08-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_fix_vlan_id_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='action',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='device',
            name='pub_rsa',
        ),
    ]
