# Generated by Django 4.2.23 on 2025-08-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_remove_device_fields'),
    ]

    operations = [
        # Remove OTP tables created by django-otp
        migrations.RunSQL(
            "DROP TABLE IF EXISTS otp_static_staticdevice;",
            reverse_sql="-- Cannot reverse OTP static device table removal"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS otp_static_statictoken;",
            reverse_sql="-- Cannot reverse OTP static token table removal"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS otp_totp_totpdevice;",
            reverse_sql="-- Cannot reverse OTP TOTP device table removal"
        ),
    ]
