# Generated by Django 4.2 on 2025-07-29 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_remove_securitysettings_block_shared_connections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='Enable_TTL_Modification',
            field=models.BooleanField(default=False, help_text='Apply iptables TTL mangle rules to prevent sharing (MikroTik-style)', verbose_name='Enable TTL Modification'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='Modified_TTL_Value',
            field=models.IntegerField(default=1, help_text='TTL value to set for violating devices (1 = blocks sharing completely)', verbose_name='Modified TTL Value'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='TTL_Modification_After_Violations',
            field=models.IntegerField(default=10, help_text='Number of violations before applying TTL modification rules', verbose_name='TTL Modify After Violations'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='TTL_Rule_Duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), help_text='How long to keep TTL modification rules active', verbose_name='TTL Rule Duration'),
        ),
        migrations.CreateModel(
            name='TTLFirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_MAC', models.CharField(max_length=255, verbose_name='Device MAC')),
                ('Rule_Type', models.CharField(choices=[('mangle_ttl', 'TTL Modification (Mangle)'), ('drop_sharing', 'Drop Sharing Traffic'), ('limit_bandwidth', 'Bandwidth Limiting')], default='mangle_ttl', max_length=20, verbose_name='Rule Type')),
                ('Rule_Status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', max_length=10, verbose_name='Rule Status')),
                ('TTL_Value', models.IntegerField(help_text='TTL value being applied (usually 1)', verbose_name='TTL Value')),
                ('Iptables_Chain', models.CharField(default='FORWARD', max_length=50, verbose_name='Iptables Chain')),
                ('Rule_Command', models.TextField(help_text='Full iptables command used', verbose_name='Iptables Command')),
                ('Created_At', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('Expires_At', models.DateTimeField(verbose_name='Expires At')),
                ('Last_Checked', models.DateTimeField(auto_now=True, verbose_name='Last Checked')),
                ('Violation_Count', models.IntegerField(default=0, verbose_name='Violations That Triggered Rule')),
                ('Admin_Notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
            ],
            options={
                'verbose_name': 'TTL Firewall Rule',
                'verbose_name_plural': 'TTL Firewall Rules',
                'ordering': ['-Created_At'],
                'unique_together': {('Device_MAC', 'Rule_Type')},
            },
        ),
    ]
