# Generated by Django 4.2 on 2025-07-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_networkintelligence_trafficanalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthenticatedClients',
            fields=[
            ],
            options={
                'verbose_name': 'Unauthenticated Client',
                'verbose_name_plural': 'Unauthenticated Clients (Connected to AP)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.clients',),
        ),
    ]
